name: Setup Ember

runs:
  using: "composite"
  steps:
    - name: Checkout deepinthink/ember
      uses: actions/checkout@v4
      with:
        repository: deepinthink/ember
        path: deepinthink/ember

    - name: Build && Install ember-spring-blockchain
      shell: bash
      run: cd deepinthink/ember/infrastructure/framework/java/ember-spring-blockchain && ./mvnw install -B

    - name: Build && Install ember-spring-blockchain-benchmark
      shell: bash
      run: cd deepinthink/ember/infrastructure/benchmark/java/ember-spring-blockchain-benchmark && ./mvnw install -B
